language: r
sudo: false
cache: packages

r:
  - release
  - devel

r_check_args: "--as-cran"

r_github_packages:
  - tidyverse/dplyr

after_success:
  - Rscript -e 'library(covr);codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
